version: '3.7'

services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/ssh
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
    environment:
      - TZ=Europe\London
      - DB_URL=mongodb://mongo:27017/petio
    entrypoint: ['zsh', '-c', 'while sleep 1000; do :; done']

  mongo:
    env_file: .env
    image: mongo:4.4.0
    container_name: 'petio-mongo-${MONGO_CONTAINER_ID:-local}'
    hostname: mongo
    volumes:
      - ./data/db:/data/db
